recipes/urls.py
from django.urls import path

from recipes.views import (
    RecipeCreateView,
    RecipeDeleteView,
    RecipeUpdateView,
    log_rating,
    RecipeDetailView,
    RecipeListView,
    UserListView,
    ShoppingItemListViiew,
    create_shopping_item,
    delete_all_shopping_items,
)


urlpatterns = [
    path("", RecipeListView.as_view(), name="recipes_list"),
    path("<int:pk>/", RecipeDetailView.as_view(), name="recipe_detail"),
    path("<int:pk>/delete/", RecipeDeleteView.as_view(), name="recipe_delete"),
    path("new/", RecipeCreateView.as_view(), name="recipe_new"),
    path("<int:pk>/edit/", RecipeUpdateView.as_view(), name="recipe_edit"),
    path("<int:recipe_id>/ratings/", log_rating, name="recipe_rating"),
    path("users/", UserListView.as_view(), name="users_list"),
    path(
        "shopping_items/",
        ShoppingItemListViiew.as_view(),
        name="shopping_items",
    ),
    path(
        "shopping_items/create/",
        create_shopping_item,
        name="shopping_item_create",
    ),
    path(
        "shopping_items/delete",
        delete_all_shopping_items,
        name="shopping_item_delete",
    ),
]

scrumptious/urls.py
from django.contrib import admin
from django.urls import include, path, reverse_lazy
from django.views.generic.base import RedirectView
from django.contrib.auth import views as auth_views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("users/", include("recipes.urls")),
    path("accounts/login/", auth_views.LoginView.as_view(), name="login"),
    path("accounts/logout", auth_views.LogoutView.as_view(), name="logout"),
    path("recipes/", include("recipes.urls")),
    path("tags/", include("tags.urls")),
    path("mealplans/", include("mealplans.urls")),
    path(
        "",
        RedirectView.as_view(url=reverse_lazy("recipes_list")),
        name="home",
    ),
]

tags/urls.py
from django.urls import path

from tags.views import (
    TagListView,
    TagDeleteView,
    TagDetailView,
    TagCreateView,
    TagUpdateView,
)

urlpatterns = [
    path("", TagListView.as_view(), name="tags_list"),
    path("<int:pk>/", TagDetailView.as_view(), name="tag_detail"),
    path("<int:pk>/delete/", TagDeleteView.as_view(), name="tag_delete"),
    path("new/", TagCreateView.as_view(), name="tag_new"),
    path("<int:pk>/edit/", TagUpdateView.as_view(), name="tag_edit"),
]

recipes/models.py
from django.db import models
from django.shortcuts import redirect
from django.core.validators import MaxValueValidator, MinValueValidator
from django.conf import settings


USER_MODEL = settings.AUTH_USER_MODEL


# Create your models here.
class Recipe(models.Model):
    name = models.CharField(max_length=125)
    author = models.ForeignKey(
        USER_MODEL, related_name="recipes", on_delete=models.CASCADE, null=True
    )
    description = models.TextField()
    image = models.URLField(null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    edited_by = models.ForeignKey(
        USER_MODEL,
        related_name="recipeseditedby",
        on_delete=models.CASCADE,
        null=True,
    )
    servings = models.PositiveSmallIntegerField(
        validators=[
            MaxValueValidator(5),
            MinValueValidator(1),
        ],
        null=True,
    )

    def __str__(self):
        return self.name + " by " + str(self.author)


class Rating(models.Model):
    value = models.PositiveSmallIntegerField(
        validators=[
            MaxValueValidator(5),
            MinValueValidator(1),
        ]
    )
    recipe = models.ForeignKey(
        "Recipe",
        related_name="ratings",
        on_delete=models.CASCADE,
    )


class ShoppingItem(models.Model):
    user = models.ForeignKey(
        USER_MODEL, related_name="shopping_items", on_delete=models.CASCADE
    )
    food_item = models.ForeignKey("FoodItem", on_delete=models.PROTECT)

    def get_queryset(self):
        return ShoppingItem.objects.filter(user=self.request.user)

    def __str__(self):
        return str(self.food_item) + " for " + str(self.user)


class Measure(models.Model):
    name = models.CharField(max_length=30, unique=True)
    abbreviation = models.CharField(max_length=10, unique=True)

    def __str__(self):
        return self.name


class FoodItem(models.Model):
    name = models.CharField(max_length=100, unique=True)

    def __str__(self):
        return self.name


class Ingredient(models.Model):
    amount = models.FloatField(validators=[MaxValueValidator(20)])
    recipe = models.ForeignKey(
        "Recipe",
        related_name="ingredients",
        on_delete=models.CASCADE,
    )
    measure = models.ForeignKey("Measure", on_delete=models.PROTECT)
    food = models.ForeignKey("FoodItem", on_delete=models.PROTECT)

    def __str__(self):
        amount = str(self.amount)
        measure = self.measure.name
        food = self.food.name
        return amount + " " + measure + " " + food


class Step(models.Model):
    recipe = models.ForeignKey(
        "Recipe",
        related_name="steps",
        on_delete=models.CASCADE,
    )
    order = models.PositiveSmallIntegerField()
    directions = models.CharField(max_length=300)
    food_items = models.ManyToManyField("FoodItem", blank=True)

    def __str__(self):
        return str(self.order) + ". " + self.directions

recipes/forms.py
from django import forms


from recipes.models import Recipe


# class RecipeForm(forms.ModelForm):
#     class Meta:
#         model = Recipe
#         fields = [
#             "name",
#             "author",
#             "description",
#             "image",
#         ]


from recipes.models import Rating


class RatingForm(forms.ModelForm):
    class Meta:
        model = Rating
        fields = ["value"]


class ServingForm(forms.ModelForm):
    class Meta:
        model = Recipe
        fields = ["servings"]

recipes/views.py
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.views.generic.list import ListView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.conf import settings
from django.contrib.auth.models import User
from recipes.forms import RatingForm, ServingForm
from django.views.decorators.http import require_http_methods
from psycopg2 import IntegrityError

USER_MODEL = settings.AUTH_USER_MODEL
# from recipes.forms import RecipeForm
from recipes.models import USER_MODEL, Recipe, ShoppingItem, Ingredient


def log_rating(request, recipe_id):
    if request.method == "POST":
        form = RatingForm(request.POST)
        if form.is_valid():
            rating = form.save(commit=False)
            try:
                rating.recipe = Recipe.objects.get(pk=recipe_id)
                rating.save()
                return redirect("recipe_detail", pk=recipe_id)
            except Recipe.DoesNotExist:
                return redirect("recipes_list")


class RecipeListView(ListView):
    model = Recipe
    template_name = "recipes/list.html"
    paginate_by = 2


class UserListView(ListView):
    model = User
    context_object_name = "users"
    template_name = "recipes/users.html"

    # def get_queryset(self):
    #     qs = super().get_queryset()
    #     return qs.exclude(len(self.recipes.all) < 1)


class RecipeDetailView(DetailView):
    model = Recipe
    template_name = "recipes/detail.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["rating_form"] = RatingForm()

        context["servings"] = self.request.GET.get("servings")

        user_shoppinglist = []
        for item in self.request.user.shopping_items.all():
            user_shoppinglist.append(item.food_item)

        context["food_in_shopping_list"] = user_shoppinglist

        print(self.request.user)

        return context


class RecipeCreateView(LoginRequiredMixin, CreateView):
    model = Recipe
    template_name = "recipes/new.html"
    fields = ["name", "servings", "ßdescription", "image"]
    success_url = reverse_lazy("recipes_list")

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class RecipeUpdateView(LoginRequiredMixin, UpdateView):
    model = Recipe
    template_name = "recipes/edit.html"
    fields = ["name", "servings", "description", "image"]
    success_url = reverse_lazy("recipes_list")

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class RecipeDeleteView(LoginRequiredMixin, DeleteView):
    model = Recipe
    template_name = "recipes/delete.html"
    success_url = reverse_lazy("recipes_list")


class ShoppingItemListViiew(LoginRequiredMixin, ListView):
    model = ShoppingItem
    template_name = "recipes/shopping_items/list.html"

    def get_queryset(self):
        return ShoppingItem.objects.filter(user=self.request.user)


@require_http_methods(["POST"])
def create_shopping_item(request):
    ingredient_id = request.POST.get("ingredient_id")

    ingredient = Ingredient.objects.get(id=ingredient_id)
    user = request.user

    try:
        ShoppingItem.objects.create(food_item=ingredient.food, user=user)
    except IntegrityError:
        pass

    return redirect("recipe_detail", pk=ingredient.recipe.id)


def delete_all_shopping_items(request):
    ShoppingItem.objects.filter(user=request.user).delete()
    return redirect("shopping_items")

recipes/templates/recipes/delete.html
{% extends 'base.html' %}

{% block content %}
  <main>
    <div class="delete-form">
      <form method="post">
        {% csrf_token %}
        <p>Are you sure you want to delete "{{ recipe }}"?</p>
        {{ form.as_p }}
        <div>
          <button class="button">Delete</button>
        </div>
      </form>
    </div>
  </main>
  {% endblock content %}

recipes/templates/recipes/detail.html
{% extends 'base.html' %}
{% load markdownify %} 
{% load resizer %}

{% block content %}
  <main class="recipe-detail">
    <div>
      <a href="{% url 'recipe_edit' recipe.id %}">Edit</a>
      <a href="{% url 'recipe_delete' recipe.id %}">Delete</a>
    </div>
    {% if recipe.image %}
      <img src="{{ recipe.image }}" class="pull-right">
    {% endif %}
    <h1>{{ recipe.name }}</h1>
    <h2>by: {{ recipe.author | default_if_none:"Unknown" }}</h2>
    <p>
      Created on {{ recipe.created }} |
      Updated on {{ recipe.updated }}  | 
      {% if recipe.servings %}
      Serves {{ recipe.servings }}

    </p>
    <form method="get">
      {% csrf_token %}
      <div class="rating-form-grid"> 
        <input required type="number" name="servings">
        <button class="button">Resize</button>
      </div> 
    </form> 
    {% endif %}
    <form method="post" action="{% url 'recipe_rating' recipe.id %}">
      {% csrf_token %}
      <div class="rating-form-grid">
        {{ rating_form.as_p }}
        <button class="button">Rate</button>
      </div>
    </form>
    <p>Tags: {% for tag in recipe.tags.all %}{{ tag.word }} {% endfor %}</p>
    {{ recipe.description | markdownify }}
    <h2>Ingredients</h2>
    <table>
      <thead>
        <tr>
          <th colspan="2">Amount</th>
          <th>Food item</th>
        </tr>
      </thead>
      <tbody>
        {% for ingredient in recipe.ingredients.all %}
          <tr>
    
            <td>{{ ingredient|resize_to:servings }}</td>
            <td>{{ ingredient.measure.name }}</td>
            <td>{{ ingredient.food.name }}</td>
          
            <td> 
              {% if ingredient.food not in food_in_shopping_list %}
              <form method="Post" action="{% url 'shopping_item_create' %}"> 
                {% csrf_token %}
                <input type="hidden" name="ingredient_id" value="{{ ingredient.id }}">
                <button>+ shopping list</button> 
              </form> 
              {% elif ingredient.food in food_in_shopping_list %}
              <p>This item is already in shopping list!</p>
              {% endif %}

            </td> 
          </tr>





        {% endfor %}
      </tbody>
    </table>
    <h2>Steps</h2>
    <ol>
      {% for step in recipe.steps.all %}
        <li>{{ step.directions }}</li>
      {% endfor %}
    </ol>
  </main>
  {% endblock content %}

recipes/templates/recipes/edit.html
{% extends 'base.html' %}

{% block content %}
  <main class="recipe-form">
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <div class="control">
        <button class="button">Update</button>
      </div>
    </form>
  </main>
{% endblock content %}

recipes/templates/recipes/list.html
{% extends 'paginate.html' %}


{% comment %} {% block pagination %}
   <div class="pagination">
    <span class="step-links">
      {% if page_obj.has_previous %}
        <a href="?page=1">&laquo; first</a>
        <a href="?page={{ page_obj.previous_page_number }}">previous</a>
      {% endif %}

      <span class="current">
        Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
      </span>

      {% if page_obj.has_next %}
        <a href="?page={{ page_obj.next_page_number }}">next</a>
        <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
      {% endif %}
    </span>
  </div> 
{% endblock pagination %} {% endcomment %}

{% block content %}
  <main class="recipe-grid">
    {% for recipe in recipe_list %}
      <div class="recipe-card">
        <h2 class="recipe-card-title">
          <a href="{% url 'recipe_detail' recipe.pk %}">{{ recipe.name }}</a>
        </h2>
        <p class="recipe-card-date">{{ recipe.updated }}</p>
      </div>
    {% endfor %}
  </main>
  {% endblock content %}

recipes/templates/recipes/new.html
{% extends 'base.html' %}

{% block content %}
  <main class="recipe-form">
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <div class="control">
        <button class="button">Create</button>
      </div>
    </form>
  </main>
  {% endblock content %}

recipes/templates/recipes/test.html
{% extends 'base.html' %}
{% load markdownify %}
{% block content %}
  <main class="tag-detail">
    <div>
      {% comment %} <a href="{% url 'mealplan_delete' mealplans.id %}">Delete All</a>  {% endcomment %}
    </div>
    <h2>Your Shopping List: </h2>
    <ul>
        {% for item in shoppingitems %}
        <li> 
            {{ item.name }}
        </li>
    </ul> 
  </main>
  {% endfor %}
  {% endblock content %}

recipes/templates/recipes/users.html
{% extends 'base.html' %}


{% block content %}
  <main class="recipe-grid">
    {% for user in users %}
      {%if user.recipes.all %}

      <div class="recipe-card">
        <ul>
        <h2 class="recipe-card-title">Recipes written by {{ user }}</h2> 
      </div>
        {% endif %}
     
      {% for recipe in user.recipes.all %}
      <li>
        <a href="{% url 'recipe_detail' recipe.pk %}">{{ recipe }}</a>
      </li>
    
      {% endfor %}
    </ul>
    {% endfor %}
</main>
<main class="recipe-grid">
  <ul>
    {% for user in users %}
    <div class="recipe-card">
      <h2 class="recipe-card-title">
      <h2>Recipes edited by {{ user }}</h2> 
      </h2>
    </div>
    {% for recipe in user.recipeseditedby.all %}
    <li>
      <a href="{% url 'recipe_detail' recipe.pk %}">{{ recipe }}</a>
    </li>
    {% endfor %}
  {% endfor %}
  </ul>
</main> 
{% endblock content %}